nodeLinker: node-modules
npmRegistryServer: "https://registry.npmjs.org/"
enableGlobalCache: true
enableStrictSsl: false
nmMode: hardlinks-local
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - windows
    - linux
    - darwin
